// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4lBxMGYfcjM-o81amw7ls1WS8jKyG8NU',
    appId: '1:512547715504:web:1777789fb2a250ec54fe75',
    messagingSenderId: '512547715504',
    projectId: 'prestatec-5642b',
    authDomain: 'prestatec-5642b.firebaseapp.com',
    storageBucket: 'prestatec-5642b.firebasestorage.app',
    measurementId: 'G-DZ2739DH9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR7ZyPyyV2bYji-xMiJ5-JDj1hrJYaRcE',
    appId: '1:512547715504:android:2ec2c67b8bcc454954fe75',
    messagingSenderId: '512547715504',
    projectId: 'prestatec-5642b',
    storageBucket: 'prestatec-5642b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4lBxMGYfcjM-o81amw7ls1WS8jKyG8NU',
    appId: '1:512547715504:web:b693add0bbd89d6754fe75',
    messagingSenderId: '512547715504',
    projectId: 'prestatec-5642b',
    authDomain: 'prestatec-5642b.firebaseapp.com',
    storageBucket: 'prestatec-5642b.firebasestorage.app',
    measurementId: 'G-ESBYN2MC8J',
  );
}
